runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: '1.0'
handlers:
- url: (/admin)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: required
  secure: optional
- url: /
  script: unused
  login: required
  secure: optional
- url: /admin
  script: unused
  login: admin
  secure: optional
- url: /.*/
  script: unused
  login: required
  secure: optional
- url: /_ah/.*
  script: unused
  login: required
  secure: optional
- url: /.*\.jsp
  script: unused
  login: required
  secure: optional
- url: /deletePoll
  script: unused
  login: required
  secure: optional
- url: /vote
  script: unused
  login: required
  secure: optional
- url: .*\.jsp
  script: unused
  login: optional
  secure: optional
- url: /editIdea
  script: unused
  login: required
  secure: optional
- url: /deleteIdea
  script: unused
  login: required
  secure: optional
- url: /viewPoll
  script: unused
  login: required
  secure: optional
- url: /createIdea
  script: unused
  login: required
  secure: optional
- url: /openPoll
  script: unused
  login: required
  secure: optional
- url: /sharePoll
  script: unused
  login: required
  secure: optional
- url: /closePoll
  script: unused
  login: required
  secure: optional
- url: /hello
  script: unused
  login: required
  secure: optional
- url: /createPoll
  script: unused
  login: required
  secure: optional
- url: /BrowseIdeas
  script: unused
  login: required
  secure: optional
